### PR TITLE
Resurrection sprint: python3 support.

### PR DESCRIPTION
**Pull request by janjaapdriessen**

### CODE REVIEW

**Comment by icemac** [comment]
Hi, are there any plans for progress on this PR?

**Comment by clozinski** [comment]
Hello.
I am pleased to say that there is once again a working version of grokproject on Python 2.
There is an unpublished version of grokproject on Python 3.
I am in the process of upgrading my website to Python 3.
I wanted to go the the resurrection sprint, but then they told me that Zope 4 is really an upgrade of Zope 2.
Talk about confusing. 

So yes I do volunteer to review this pull request, test it out on my software, but I am not sure when that will happen.  I am just completing a startup accelerator, and we are in the busy fall season.  This issue is very important to me. 

Does that answer your question?  What needs to be done with this pull request?

I know Paul Sephton and I are very actively using Grok, and both are contributing stuff. 
And there is another volunteer who did the Python 3 port. 

Warm Regards
Chris

**Comment by icemac** [comment]
> I wanted to go the the resurrection sprint, but then they told me that Zope 4 is really an upgrade of Zope 2.

@clozinski Yes Zope 4 is there to remove the confusion which was generated by Zope 3. Because Zope 3 never really took off and should have been named completely different when it was created. But once there was the promise to be able to run Zope 2 code in Zope 3 using some glue code – which actually  never was written.

**Comment by clozinski** [comment]
I totally agree with you that Zope 3 was a brand disaster.  

Maybe Grok makes a better brand name.

**Comment by icemac** [comment]
Wow, TravisCI is green now!

**Comment by janwijbrand** [comment]
I don't understand how it could've been green. z3c.autoinclude is acting up at least on my machine.

**Pull request merged**
